apiVersion: v1
kind: Service
metadata:
  name: fineract
  labels:
    app: fineract
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8078
  selector:
    app: fineract
  type: LoadBalancer
